# Generated by Django 5.2.10 on 2026-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gold Store', max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, upload_to='site_settings/', verbose_name='Логотип')),
                ('phones', models.TextField(blank=True, help_text='По одному в строке', verbose_name='Телефоны')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Часы работы')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp', models.URLField(blank=True, help_text='Например, https://wa.me/996555123456', verbose_name='WhatsApp')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('about', models.TextField(blank=True, verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
