# Generated by Django 5.2.10 on 2026-10-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='phones',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Например, «Контакт-центр»', max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['order', 'id'],
            },
        ),
    ]
