# Generated by Django 5.2.10 on 2026-10-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_phones_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='phone',
            name='label_ky',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (кыргызча)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_en',
            field=models.TextField(blank=True, verbose_name='О нас (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_ky',
            field=models.TextField(blank=True, verbose_name='О нас (кыргызча)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ky',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (кыргызча)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Часы работы (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_ky',
            field=models.CharField(blank=True, max_length=255, verbose_name='Часы работы (кыргызча)'),
        ),
    ]
