# Generated by Django 5.2.10 on 2026-10-04 13:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро')], max_length=10, verbose_name='металл')),
                ('fineness', models.PositiveSmallIntegerField(help_text='Например: 585, 750, 925', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='проба')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='цена за 1 г, сом')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть пробу, не удаляя её', verbose_name='показывать на сайте')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'проба',
                'verbose_name_plural': 'пробы',
                'ordering': ['metal', '-fineness'],
                'constraints': [models.UniqueConstraint(fields=('metal', 'fineness'), name='unique_metal_fineness')],
            },
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_label', models.CharField(max_length=50, verbose_name='проба')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('price', 'Изменена цена'), ('deleted', 'Удалена')], max_length=10, verbose_name='действие')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='было')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='кто')),
                ('probe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='rates.probe', verbose_name='проба')),
            ],
            options={
                'verbose_name': 'запись истории',
                'verbose_name_plural': 'история изменений',
                'ordering': ['-changed_at'],
            },
        ),
    ]
