# Generated by Django 5.2.10 on 2026-10-06 10:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def add_default_weights(apps, schema_editor):
    """Кнопки, которые раньше были зашиты в шаблон, чтобы после обновления на сайте ничего не пропало."""
    QuickWeight = apps.get_model("rates", "QuickWeight")
    for grams in (1, 2, 3, 4, 5, 10, 15, 25, 50):
        QuickWeight.objects.get_or_create(grams=Decimal(grams))


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, help_text='Например: 1, 2.5, 10', max_digits=8, unique=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='вес, г')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть кнопку, не удаляя её', verbose_name='показывать на сайте')),
            ],
            options={
                'verbose_name': 'быстрый вес',
                'verbose_name_plural': 'быстрые веса',
                'ordering': ['grams'],
            },
        ),
        migrations.RunPython(add_default_weights, migrations.RunPython.noop),
    ]
